### ISSUE TITLE
cannot find package `react` error when running `payload` in a standalone script

### ISSUE THREAD

**Issue by oladayo21** [payloadcms/payload-3.0-demo#160] opened 2024-04-28 15:27 UTC
I get the following error when trying to run a one-time script using the payload local API. The error seems to point to `react` being imported somewhere in the config loading process. Not sure if I am the one doing something wrong, I have an example repo set up [here](https://github.com/oladayo21/payload-standalone).

Error gotten  is: 
```typescript
Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'react' imported from /xxxxx/xxxxxx/projects/payload-standalone/node_modules/.pnpm/payload@3.0.0-beta.18_@swc+core@1.4.17_@swc+types@0.1.6_graphql@16.8.1/node_modules/payload/dist/utilities/isReactComponent.js
    at packageResolve (node:internal/modules/esm/resolve:853:9)
    at moduleResolve (node:internal/modules/esm/resolve:910:20)
    at defaultResolve (node:internal/modules/esm/resolve:1130:11)
    at nextResolve (node:internal/modules/esm/hooks:865:28)
    at d (file:///Users/ofagbemi/projects/payload-standalone/node_modules/.pnpm/tsx@4.7.3/node_modules/tsx/dist/esm/index.mjs:5:34)
    at F (file:///Users/ofagbemi/projects/payload-standalone/node_modules/.pnpm/tsx@4.7.3/node_modules/tsx/dist/esm/index.mjs:5:1169)
    at nextResolve (node:internal/modules/esm/hooks:865:28)
    at resolve (/Users/ofagbemi/projects/payload-standalone/node_modules/.pnpm/payload@3.0.0-beta.18_@swc+core@1.4.17_@swc+types@0.1.6_graphql@16.8.1/node_modules/payload/src/bin/loader/index.ts:125:10)
    at async nextResolve (node:internal/modules/esm/hooks:865:22)
    at async Hooks.resolve (node:internal/modules/esm/hooks:303:24) {
  code: 'ERR_MODULE_NOT_FOUND'
}
```

**Comment by jmikrut** [comment] 2024-04-28 16:08
@AlessioGr let's get a test added for the scenario in this reproduction repo. I have not looked yet but it might be similar to https://github.com/payloadcms/payload-3.0-demo/issues/147 where symlinks are messing with stuff.

**Comment by AlessioGr** [comment] 2024-04-28 20:09
Looks like this is actually a bug in our importConfig helper. Fixed it in https://github.com/payloadcms/payload/pull/6090/commits/cd5e8d7b525379637871e355c10413947b1d36e9

@jmikrut I've changed our loader tests to use our importConfig helper rather than calling node:register manually, so that these issues will be caught in the future

**Comment by AlessioGr** [comment] 2024-05-01 14:45
Fixed by https://github.com/payloadcms/payload/pull/6090

**Closed by AlessioGr** 2024-05-01 14:45 UTC
Labels: reproduced
