### ISSUE TITLE
plugin-cloud-storage FileUploadError when resaving image

### ISSUE THREAD

**Issue by HarleySalas** [payloadcms/payload-3.0-demo#134] opened 2024-04-22 11:32 UTC
With `plugin-cloud-storage` and local storage disabled, I get the following error when I try to update an already existing upload:

```
ERROR: FileUploadError: There was a problem while uploading the file.
    at generateFileData (webpack-internal:///(rsc)/./node_modules/.pnpm/payload@3.0.0-beta.11_@swc+core@1.4.16_@swc+types@0.1.6/node_modules/payload/dist/uploads/generateFileData.js:62:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async updateByIDOperation (webpack-internal:///(rsc)/./node_modules/.pnpm/payload@3.0.0-beta.11_@swc+core@1.4.16_@swc+types@0.1.6/node_modules/payload/dist/collections/operations/updateByID.js:118:61)
    at async Object.updateByID (webpack-internal:///(rsc)/./node_modules/.pnpm/@payloadcms+next@3.0.0-beta.11_@types+react@18.2.79_http-status@1.6.2_monaco-editor@0.47.0_ne_fiws62zumohsretfbplufbz3pe/node_modules/@payloadcms/next/dist/routes/rest/collections/updateByID.js:23:17)
    at async eval (webpack-internal:///(rsc)/./node_modules/.pnpm/@payloadcms+next@3.0.0-beta.11_@types+react@18.2.79_http-status@1.6.2_monaco-editor@0.47.0_ne_fiws62zumohsretfbplufbz3pe/node_modules/@payloadcms/next/dist/routes/rest/index.js:573:31)
    at async D:\dev\(removed-for-privacy)\node_modules\.pnpm\next@14.3.0-canary.7_@babel+core@7.24.4_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\compiled\next-server\app-route.runtime.dev.js:6:53211
    at async e_.execute (D:\dev\(removed-for-privacy)\node_modules\.pnpm\next@14.3.0-canary.7_@babel+core@7.24.4_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\compiled\next-server\app-route.runtime.dev.js:6:44492)
    at async e_.handle (D:\dev\(removed-for-privacy)\node_modules\.pnpm\next@14.3.0-canary.7_@babel+core@7.24.4_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\compiled\next-server\app-route.runtime.dev.js:6:54465)
    at async doRender (D:\dev\(removed-for-privacy)\node_modules\.pnpm\next@14.3.0-canary.7_@babel+core@7.24.4_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\server\base-server.js:1359:42)
    at async cacheEntry.responseCache.get.routeKind (D:\dev\(removed-for-privacy)\node_modules\.pnpm\next@14.3.0-canary.7_@babel+core@7.24.4_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\server\base-server.js:1573:40)
    at async DevServer.renderToResponseWithComponentsImpl (D:\dev\(removed-for-privacy)\node_modules\.pnpm\next@14.3.0-canary.7_@babel+core@7.24.4_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\server\base-server.js:1493:28)
    at async DevServer.renderPageComponent (D:\dev\(removed-for-privacy)\node_modules\.pnpm\next@14.3.0-canary.7_@babel+core@7.24.4_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\server\base-server.js:1910:24)
    at async DevServer.renderToResponseImpl (D:\dev\(removed-for-privacy)\node_modules\.pnpm\next@14.3.0-canary.7_@babel+core@7.24.4_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\server\base-server.js:1948:32)
    at async DevServer.pipeImpl (D:\dev\(removed-for-privacy)\node_modules\.pnpm\next@14.3.0-canary.7_@babel+core@7.24.4_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\server\base-server.js:895:25)
    at async NextNodeServer.handleCatchallRenderRequest (D:\dev\(removed-for-privacy)\node_modules\.pnpm\next@14.3.0-canary.7_@babel+core@7.24.4_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\server\next-server.js:272:17)
    at async DevServer.handleRequestImpl (D:\dev\(removed-for-privacy)\node_modules\.pnpm\next@14.3.0-canary.7_@babel+core@7.24.4_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\server\base-server.js:791:17)
    at async D:\dev\(removed-for-privacy)\node_modules\.pnpm\next@14.3.0-canary.7_@babel+core@7.24.4_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\server\dev\next-dev-server.js:339:20
    at async Span.traceAsyncFn (D:\dev\(removed-for-privacy)\node_modules\.pnpm\next@14.3.0-canary.7_@babel+core@7.24.4_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\trace\trace.js:154:20)
    at async DevServer.handleRequest (D:\dev\(removed-for-privacy)\node_modules\.pnpm\next@14.3.0-canary.7_@babel+core@7.24.4_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\server\dev\next-dev-server.js:336:24)
    at async invokeRender (D:\dev\(removed-for-privacy)\node_modules\.pnpm\next@14.3.0-canary.7_@babel+core@7.24.4_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\server\lib\router-server.js:174:21)
    at async handleRequest (D:\dev\(removed-for-privacy)\node_modules\.pnpm\next@14.3.0-canary.7_@babel+core@7.24.4_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\server\lib\router-server.js:353:24)
    at async requestHandlerImpl (D:\dev\(removed-for-privacy)\node_modules\.pnpm\next@14.3.0-canary.7_@babel+core@7.24.4_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\server\lib\router-server.js:377:13)
    at async Server.requestListener (D:\dev\(removed-for-privacy)\node_modules\.pnpm\next@14.3.0-canary.7_@babel+core@7.24.4_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\server\lib\start-server.js:141:13)
```

So, I cannot update things like the alt, or change image `sizes` and force it to reformat.

`3.0.0-beta.11`

**Comment by JessChowdhury** [comment] 2024-04-22 12:32
Hi @HarleySalas - what [adapter](https://github.com/payloadcms/payload/tree/main/packages/plugin-cloud-storage#features) are you using with the `plugin-cloud-storage`?  (Azure / S3 / GCS)

**Comment by denolfe** [comment] 2024-04-22 18:50
Duplicate of #131

**Closed by denolfe** 2024-04-22 18:50 UTC
