### ISSUE TITLE
SEO Plugin installation Error 

### ISSUE THREAD

**Issue by AdvithShetty** [payloadcms/payload-3.0-demo#173] opened 2024-05-03 09:27 UTC
I used `npm i @payloadcms/plugin-seo@3.0.0-beta.10 ` to install the plugin and it worked. But now, I'm encountering an error while trying to use the Payload SEO plugin with Payload CMS version 3.0, following the official documentation. Despite searching online, I haven't found resources beyond the Payload documentation. Could you guide me on how to properly integrate it into a collection?

ERROR:

```
Import trace for requested module:
./payload.config.ts
./app/(payload)/admin/[[...segments]]/page.tsx
 GET /admin 200 in 2163ms
 ⨯ payload.config.ts (50:15) @ eval
 ⨯ TypeError: (0 , _payloadcms_plugin_seo__WEBPACK_IMPORTED_MODULE_4__.default) is not a function
    at eval (webpack-internal:///(rsc)/./payload.config.ts:77:75)
    at (rsc)/./payload.config.ts (C:\project\website\project\.next\server\app\(payload)\admin\[[...segments]]\page.js:610:1)
    at __webpack_require__ (C:\project\website\project\.next\server\webpack-runtime.js:33:43)
    at eval (webpack-internal:///(rsc)/./app/(payload)/layout.tsx:7:73)
    at (rsc)/./app/(payload)/layout.tsx (C:\project\website\project\.next\server\app\(payload)\admin\[[...segments]]\page.js:478:1)
    at Function.__webpack_require__ (C:\project\website\project\.next\server\webpack-runtime.js:33:43)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async collectGenerateParams (C:\project\website\project\node_modules\next\dist\build\utils.js:920:21)
    at async Object.loadStaticPaths (C:\project\website\project\node_modules\next\dist\server\dev\static-paths-worker.js:46:13) {
  type: 'TypeError',
  page: '/admin'
}
  48 |   },
  49 |   plugins: [
> 50 |     seoPlugin({
     |               ^
  51 |       collections: ["pages"],
  52 |       uploadsCollection: "media",
  53 |       generateTitle: ({ doc }) => `Website.com — ${doc.title.value}`,
 ⨯ payload.config.ts (50:15) @ eval
 ⨯ TypeError: (0 , _payloadcms_plugin_seo__WEBPACK_IMPORTED_MODULE_4__.default) is not a function
    at eval (webpack-internal:///(rsc)/./payload.config.ts:77:75)
    at (rsc)/./payload.config.ts (C:\project\website\project\.next\server\app\(payload)\admin\[[...segments]]\page.js:610:1)
    at __webpack_require__ (C:\project\website\project\.next\server\webpack-runtime.js:33:43)
    at eval (webpack-internal:///(rsc)/./app/(payload)/layout.tsx:7:73)
    at (rsc)/./app/(payload)/layout.tsx (C:\project\website\.next\server\app\(payload)\admin\[[...segments]]\page.js:478:1)
    at Function.__webpack_require__ (C:\projects\website\.next\server\webpack-runtime.js:33:43)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async collectGenerateParams (C:\project\website\website\igauge\node_modules\next\dist\build\utils.js:920:21)
    at async Object.loadStaticPaths (C:\project\website\igauge\node_modules\next\dist\server\dev\static-paths-worker.js:46:13) {
  type: 'TypeError',
  page: '/admin'
}
  48 |   },
  49 |   plugins: [
> 50 |     seoPlugin({
     |               ^
  51 |       collections: ["pages"],
  52 |       uploadsCollection: "media",
  53 |       generateTitle: ({ doc }) => `Website.com — ${doc.title.value}`,
 GET /admin 500 in 1317ms

```

My Config file :

```
import { postgresAdapter } from "@payloadcms/db-postgres";
import { lexicalEditor } from "@payloadcms/richtext-lexical"; // editor-import
import path from "path";
import { buildConfig } from "payload/config";
import { fileURLToPath } from "url";
import seoPlugin from "@payloadcms/plugin-seo";

import { Users } from "./collections/Users";
import Institutions from "./collections/Institutions";
import Media from "./collections/Media";
import Blogs from "./collections/Blogs";
import Blogscategory from "@/collections/Blogscategory";
import RatingBadges from "@/collections/RatingBadges";
import Events from "@/collections/Events";
import SubjectName from "@/collections/Subjects";
import Category from "@/collections/Category";
import HeaderMenu from "@/Global/HeaderMenu";
import Footer from "@/Global/Footer";
import General from "@/Global/General";
import Pages from "@/collections/Pages";
import Features from "@/collections/Features";

const filename = fileURLToPath(import.meta.url);
const dirname = path.dirname(filename);

export default buildConfig({
  admin: {
    user: Users.slug,
  },
  collections: [
    Users,
    Institutions,
    Features,
    RatingBadges,
    SubjectName,
    Category,
    Pages,
    Media,
    Blogs,
    Blogscategory,
    Events,
  ],
  globals: [General, HeaderMenu, Footer],
  editor: lexicalEditor({}),
  secret: process.env.PAYLOAD_SECRET || "",
  typescript: {
    outputFile: path.resolve(dirname, "payload-types.ts"),
  },
  plugins: [
    seoPlugin({
      collections: ["pages"],
      uploadsCollection: "media",
      generateTitle: ({ doc }) => `Website.com — ${doc.title.value}`,
      generateDescription: ({ doc }) => doc.excerpt,
    }),
  ],
  db: postgresAdapter({
    pool: {
      connectionString: process.env.DATABASE_URI || "",
    },
  }),
  // Sharp is now an optional dependency -
  // if you want to resize images, crop, set focal point, etc.
  // make sure to install it and pass it to the config.

  // This is temporary - we may make an adapter pattern
  // for this before reaching 3.0 stable

  // sharp,
});
```

**Comment by paulpopus** [comment] 2024-05-03 13:25
Copying my reply from the other thread


@AdvithShetty Can you make sure you import with named imports instead please?
```
import { seo } from '@payloadcms/plugin-seo'
```

And make sure you're on the latest beta across all of our packages, I think it's beta 22 right now

**Comment by AdvithShetty** [comment] 2024-05-03 14:43
Hi, Thanks for the help the fields are now visible but i still see some error though on the editor,

`TS2339: Property excerpt does not exist on type T` = for the line `generateDescription: ({ doc }) => doc.excerpt`
`TS2339: Property title does not exist on type T ` =  for the line `generateTitle: ({ doc }) => `Website.com — ${doc.title.value}`,`

Is it possible to display these SEO fields only on a tab called SEO instead of on all tabs? I attached a screenshot to show what I am referring to.

![image](https://github.com/payloadcms/payload-3.0-demo/assets/87995646/b9b24467-7fef-4a73-bebd-e70f917dafef)

**Comment by paulpopus** [comment] 2024-05-03 16:15
Yeah if you add your own tab with the same name, the SEO tabs should merge I believe, but not sure if that's still the case..if not you can open a feature request on our official repo

As for your errors, those are type errors, you can type your doc as `any`

```ts
generateTitle: (data: any) => `Website.com — ${data?.doc?.title?.value}`,
generateDescription: ({ doc }: any) => doc?.excerpt?.value,
```

or you can pass your document type into the function as of 3.0 it accepts a generic.

I'm going to close this issue as it's not a bug but please feel free to seek any further help on our [discord server](https://discord.gg/payload) or [github discussions](https://github.com/payloadcms/payload/discussions)

**Closed by paulpopus** 2024-05-03 16:15 UTC
