### ISSUE TITLE
nestedDocs is not a function

### ISSUE THREAD

**Issue by standingdreams** [payloadcms/payload-3.0-demo#83] opened 2024-04-11 16:15 UTC
I have an existing application that utilizes the nested docs plugin. When I try to generate types, I receive the following error: 

```
file:///Users/spotdr/Sites/develop-site/payload.config.ts:64
        nestedDocs({
        ^

TypeError: nestedDocs is not a function
    at file:///Users/spotdr/Sites/develop-site/payload.config.ts:64:9
    at ModuleJob.run (node:internal/modules/esm/module_job:195:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:336:24)
    at async bin (file:///Users/spotdr/Sites/develop-site/node_modules/.pnpm/payload@3.0.0-beta.0_@swc+core@1.4.12_@swc+types@0.1.6/node_modules/payload/dist/bin/index.js:9:27)

Node.js v18.19.1
```

I've tried to use the package from `@payloadcms/plugin-nested-docs` and from https://github.com/payloadcms/plugin-nested-docs.

**Comment by jmikrut** [comment] 2024-04-11 16:19
can you show us your config? specifically, how you are importing the Nested Docs plugin, and how you are passing it to the `plugins` array.

I just tested this out within this repo, and it works within this repo.

Would love to help figure out the issue though. Can you share a minimally reproducible example?

**Comment by standingdreams** [comment] 2024-04-11 18:38
@jmikrut Sure. I also tried importing from `dist` directory  in the package as well. Did you want me to put together a small repo with the example? I can. I'd just need a little time.

```
import nestedDocs from '@payloadcms/plugin-nested-docs';

...

export default buildConfig({
  editor: slateEditor({}),
  secret: process.env.PAYLOAD_SECRET ?? '',
  typescript: {
    outputFile: path.resolve(dirname, 'payload-types.ts'),
  },
  db: postgresAdapter({
    pool: {
      connectionString: process.env.POSTGRES_URI || '',
    },
  }),
  admin: {
    user: Users.slug,
  },
  plugins: [
    nestedDocs({
      collections: ['categories'],
    }),
  ],
  sharp,
  collections: [Users, News, Categories],
});
```

**Comment by jmikrut** [comment] 2024-04-15 13:15
Hey @standingdreams — yes, a minimal reproduction would be great! I will keep an eye out for it when you have it. I can't reproduce on my end unfortunately.

**Comment by gitmonster** [comment] 2024-04-18 15:33
same issue here

**Comment by davelsan** [comment] 2024-04-19 11:58
Maybe a long shot, but just in case y'all missed this. The latest version changed the default export to a named export. Make sure to updated your code.

```ts
import { nestedDocs } from '@payloadcms/plugin-nested-docs';
```

**Comment by samcxps** [comment] 2024-04-19 12:04
As @davelsan mentions, I got this issue when trying to use the default version which is `1.0.12` with the `@payloadcms/next` beta. Make sure your versions line up (this goes for all plugins). 

Upgrading `@payloadcms/plugin-nested-docs` to `3.0.0-beta.11` fixed this issue for me. It is likely it is a similar issue for everyone else in this thread.

**Comment by jmikrut** [comment] 2024-04-22 12:36
Hey @samcxps thanks for clarifying this. Closing, but if anyone has any additional problems, let us know!

**Closed by jmikrut** 2024-04-22 12:36 UTC
Labels: cant-reproduce
