### ISSUE TITLE
Collection Access when used in a Relationship Field is not working properly.

### ISSUE THREAD

**Issue by HarleySalas** [payloadcms/payload-3.0-demo#206] opened 2024-05-12 10:05 UTC
I'm going to explain this, referencing terms in my [reproduction](https://github.com/HarleySalas/payload-3-reproductions/tree/relationship-create-access), because I think it will be easier to follow;

In this reproduction, you will find a `Post` `Collection` and a `Tag` `Collection`. `Tag` has access control, only allowing users with a specific role to create them. A `Tag` can also *only* be updated by an admin. Access control works perfectly fine when on the create, or update **page** for the `Tag` collection. However, when `Tag` is referenced in a relationship (by `Post` in this example), it's `access` doesn't seem to work properly.

Passing `() => true` for every `access` key in `Tag` will result in everything working fine within the modals that are presented on the collection's page which references `Tag` in a relationship. (in the case, the `Page`)

However, when I pass it a function, like [this](https://github.com/HarleySalas/payload-3-reproductions/blob/relationship-create-access/src/payload/access/access.ts), it does not work properly;
```
create: (args) => access({ args, allowedRoles: ['user'] })
```

It allows me to open the `create` modal for the related collection: `Tag`. However, there is *no save button*.

For `update`, it allows me to click the button which opens the modal for updating a `Tag`, but there is no save button. In this case, that is correct; I would expect the `user` role to not be able to update the `Tag` document, as only an `admin` should be able to, as previously mentioned. However, I do not think they should even see the icon which allows them to open the edit modal.

If you would like to run this [reproduction](https://github.com/HarleySalas/payload-3-reproductions/tree/relationship-create-access), just `pnpm install`, `docker-compose up`, change `.env.example` to `.env`, `pnpm dev` and it will automatically prefill the login with a seeded account. No additional configuration, or changes to the `.env` variables are needed. Just head to `localhost:3000/admin`, login and create a `Post`, attempting to create, or update a `Tag`.

`beta.30`, `db-postgres`

**Comment by jacobsfletch** [comment] 2024-05-16 05:34
> It allows me to open the create modal for the related collection: Tag. However, there is no save button.

Ok so it sounds like we need to completely block the user from opening this modal, since they lack create permissions in the first place. The icon should probably be completely omitted from being rendered. We should reference 2.0 for exact behavior.

> However, I do not think they should even see the icon which allows them to open the edit modal.

Well, they have read access, though, right? They can still open the modal to read the document, they just cannot update it. This is expected behavior unless I'm misunderstanding something here.

Thanks for the report as always @HarleySalas 👍

**Comment by jacobsfletch** [comment] 2024-05-16 16:27
> Ok so it sounds like we need to completely block the user from opening this modal, since they lack create permissions in the first place. The icon should probably be completely omitted from being rendered. We should reference 2.0 for exact behavior.

I just pulled down 2.0 to ensure this is in fact the current behavior, and it is. Then I pulled your repro which is running 3.0 Beta and I do see its not working as expected. This only appears to be an issue in Postgres, though. Running your demo in MongoDB works like a charm.

**Comment by jacobsfletch** [comment] 2024-05-16 20:20
Ok @HarleySalas figured it out in https://github.com/payloadcms/payload/pull/6394. Still need to write an e2e test, then I'll get this merged up.

**Closed** 2024-05-17 17:41 UTC
