### ISSUE TITLE
Unable to save collections with blocks

### ISSUE THREAD

**Issue by HarleySalas** [payloadcms/payload-3.0-demo#140] opened 2024-04-24 01:09 UTC
Postgres, localized. Can't use blocks at all.

Reproduction. beta.11 in this repo, but the issue persists with beta.14
[https://github.com/HarleySalas/payload-beta-nested-docs-issue](https://github.com/HarleySalas/payload-beta-nested-docs-issue)

1: change `.env.example` to `.env`
2: `docker-compose up`
3: `pnpm dev`

You'll notice that I've commented out the `nestedDocs` plugin, because I'd like you to see what happens when it's not enabled as well.

Create a `Page`.
If you only add a title; seems fine.

With a `Template` (blocks), I receive the following error:
```
[22:41:22] ERROR: TypeError: Cannot read properties of undefined (reading '_uuid')
    at eval (webpack-internal:///(rsc)/./node_modules/.pnpm/@payloadcms+db-postgres@3.0.0-beta.11_@types+react@18.2.79_payload@3.0.0-beta.11_react@18.2.0/node_modules/@payloadcms/db-postgres/dist/transform/write/blocks.js:26:56)
```

Then, if you repeat the same process with `nestedDocs` enabled;
```
[22:51:14] ERROR: Nested Docs plugin has had an error while adding breadcrumbs during document creation.
[22:51:14] ERROR: Cannot read properties of undefined (reading '_parentID')
    err: {
      "type": "TypeError",
      "message": "Cannot read properties of undefined (reading '_parentID')",
      "stack":
          TypeError: Cannot read properties of undefined (reading '_parentID')
              at upsertRow (webpack-internal:///(rsc)/./node_modules/.pnpm/@payloadcms+db-postgres@3.0.0-beta.11_@types+react@18.2.79_payload@3.0.0-beta.11_react@18.2.0/node_modules/@payloadcms/db-postgres/dist/upsertRow/index.js:190:110)
```
**additionally** with `nestedDocs`, it creates the document, but then deletes it.

I imagine its related, but I think the difference in behavior is a bit odd. Perhaps you want to review how that error is handled.

**Comment by jmikrut** [comment] 2024-04-25 02:19
Hey @HarleySalas — these errors were caused by `dbName` not fully functioning properly. I know you already know this from talking with you on Discord but I just fixed the hell out of them.

Now they work! So even though you've fixed your issue, now, you can still use `dbName` reliably. I've also added tests to ensure coverage. 

https://github.com/payloadcms/payload/pull/6023

Gonna close this one but at this point I think we should be fully set here. Also, `dbName` fixes will be merged shortly and will go out in the next beta.

**Closed by jmikrut** 2024-04-25 02:19 UTC
