### ISSUE TITLE
Admin access control not being respected

### ISSUE THREAD

**Issue by denolfe** [payloadcms/payload-3.0-demo#119] opened 2024-04-17 00:59 UTC
An auth collection with `admin: () => false` is still able to access the admin.

```ts
access: {
  admin: () => false,
}
```

Fix should have accompanying e2e test.

**Comment by SimonVreman** [comment] 2024-04-17 04:43
Seems to be duplicate of, or related to #117

**Closed** 2024-04-17 14:44 UTC
