### ISSUE TITLE
Cannot read properties of undefined (reading 'referencedTable')

### ISSUE THREAD

**Issue by AdvithShetty** [payloadcms/payload-3.0-demo#133] opened 2024-04-22 10:19 UTC
I am getting the following error on terminal logs when i try to save a collection item on payloadcms:

```
[15:39:30] ERROR: TypeError: Cannot read properties of undefined (reading 'referencedTable')
    at normalizeRelation (webpack-internal:///(rsc)/./node_modules/drizzle-orm/relations.js:211:56)
    at PgDialect.buildRelationalQueryWithoutPK (webpack-internal:///(rsc)/./node_modules/drizzle-orm/pg-core/dialect.js:963:101)
    at QueryPromise._getQuery (webpack-internal:///(rsc)/./node_modules/drizzle-orm/pg-core/query-builders/query.js:90:25)
    at QueryPromise._toSQL (webpack-internal:///(rsc)/./node_modules/drizzle-orm/pg-core/query-builders/query.js:105:24)
    at eval (webpack-internal:///(rsc)/./node_modules/drizzle-orm/pg-core/query-builders/query.js:69:42)
    at Object.startActiveSpan (webpack-internal:///(rsc)/./node_modules/drizzle-orm/tracing.js:14:14)
    at QueryPromise._prepare (webpack-internal:///(rsc)/./node_modules/drizzle-orm/pg-core/query-builders/query.js:68:60)
    at eval (webpack-internal:///(rsc)/./node_modules/drizzle-orm/pg-core/query-builders/query.js:114:19)
    at Object.startActiveSpan (webpack-internal:///(rsc)/./node_modules/drizzle-orm/tracing.js:14:14)
    at QueryPromise.execute (webpack-internal:///(rsc)/./node_modules/drizzle-orm/pg-core/query-builders/query.js:113:60)
    at QueryPromise.then (webpack-internal:///(rsc)/./node_modules/drizzle-orm/query-promise.js:26:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
 POST /api/pages?depth=0&fallback-locale=null 500 in 21ms

```

I am using Blocks for this collection:

```
import { CollectionConfig } from 'payload/types';

const Pages: CollectionConfig = {
    slug: 'pages',
    admin: {
        useAsTitle: 'title',
    },
    fields: [
        {
            name: 'title',
            type: 'text',
            required: true,
            label: 'Page Title',
        },
        {
            name: 'slug',
            type: 'text',
            required: true,
            label: 'Slug',
            unique: true,
        },
        {
            name: 'content',
            label: 'Page Content',
            type: 'blocks',
            blocks: [
                {
                    slug: 'textBlock',
                    labels: {
                        singular: 'Text Block',
                        plural: 'Text Blocks',
                    },
                    fields: [
                        {
                            type: 'richText',
                            name: 'text',
                            label: 'Text',
                        },
                    ],
                },
                {
                    slug: 'imageBlock',
                    labels: {
                        singular: 'Image Block',
                        plural: 'Image Blocks',
                    },
                    fields: [
                        {
                            type: 'upload',
                            name: 'image',
                            label: 'Image',
                            relationTo: 'media',
                        },
                    ],
                },
            ],
        },
    ],
};

export default Pages;
```

**Comment by JessChowdhury** [comment] 2024-04-22 12:23
Hi @AdvithShetty, are you using the Postgres database adapter?

**Comment by AdvithShetty** [comment] 2024-04-22 12:28
> Hi @AdvithShetty, are you using the Postgres database adapter?

Yes I am using postgres

**Comment by JessChowdhury** [comment] 2024-04-22 15:31
@AdvithShetty thanks. This error is commonly caused by a database entity name being too long. Postgres has a limit of 64 characters that applies to any table name, index name etc. 

To work around this issue, we have a new feature for Postgres that allows you to overwrite database names anywhere by passing the `dbName` property, this applies to collections, fields and globals. I would take a look at your database first to try and spot where the name needs to be overwritten.

We have a couple similar issues that were closed [here](https://github.com/payloadcms/payload-3.0-demo/issues/102) and [here](https://github.com/payloadcms/payload-3.0-demo/issues/72) which may also be useful to you.

**Comment by JessChowdhury** [comment] 2024-04-24 15:09
Will be closing this for now, if you need more assistance we can continue in this thread.

**Closed by JessChowdhury** 2024-04-24 15:09 UTC
