### ISSUE TITLE
[POST] to /api/users/login (admin panel) throws 405 (Vercel deployment)

### ISSUE THREAD

**Issue by aKaradzhov97** [payloadcms/payload-3.0-demo#128] opened 2024-04-19 02:12 UTC
I don't have much time now to explain extensively, but essentially I cloned the template, created a new .env file, tested locally and it works like a charm. However when I deployed it to Vercel, the post request on admin panel login throws 405 (Method not allowed). It could be that I am doing something wrong, but I think I did everything right.

Here's a link to the app:
https://payload-site.vercel.app/admin/login
I am using:
Node (18.x) locally, tried 18.x & 20.x on Vercel
MongoDB (Atlas)

I can also give any further details if necessary.

**Comment by vixalien** [comment] 2024-04-19 18:30
It seems linked to the fact that payload is sending a multipart request to the endpoint, which it doesn't support.
I sent a custom request using https://hoppscotch.io/ with the following payload (pun intended)

```json
{"email": "your@email.com", "password": "secret"}
```

and I get logged in this way. I just can't get through using the UI

**Comment by JarrodMFlesch** [comment] 2024-04-22 18:36
@aKaradzhov97 @vixalien what version of Payload 3.0 beta are you using?

**Comment by aKaradzhov97** [comment] 2024-04-22 18:38
![IMG_5899](https://github.com/payloadcms/payload-3.0-demo/assets/32314199/9bbfdc09-b2af-4da3-b930-367567c25fb6)

**Comment by JarrodMFlesch** [comment] 2024-04-22 19:35
@aKaradzhov97 @vixalien are either of the repos public?

**Comment by vixalien** [comment] 2024-04-22 19:38
@JarrodMFlesch not in my case, but if you try to deploy the demo on vercel you'll see the exact same issue as reported by @aKaradzhov97

**Comment by JarrodMFlesch** [comment] 2024-04-22 19:43
@vixalien I just did that without issue using `payload@3.0.0-beta.11` on Vercel. I setup a mongo Atlas DB, using `@payloadcms/db-mongodb@3.0.0-beta.11`, after configuring my payload config to use it I was able to deploy successfully. A public repo would be easier for me to look at and spot differences.

**Comment by aKaradzhov97** [comment] 2024-04-22 19:47
I've just changed the visibility of my repo: [Link](https://github.com/aKaradzhov97/payload-site)

**Comment by aKaradzhov97** [comment] 2024-04-22 20:07
I actually tried redeploying my repo again and this time it worked. :100:

**Comment by vixalien** [comment] 2024-04-22 21:38
I just redeployed and it worked, too!!

**Comment by JarrodMFlesch** [comment] 2024-04-22 21:46
Awesome, closing!

**Comment by jonnadams** [comment] 2024-04-26 03:34
So I'm seeing the same behavior. I can make the post via postman and I see the token in the response but I am not able to log in through the UI.

**Comment by jonnadams** [comment] 2024-04-26 03:36
I am on payload@3.0.0-beta.18 FYI

**Comment by vixalien** [comment] 2024-04-26 09:20
I randomly got the error again on a new deployment. Sometimes redeploying works okay @JarrodMFlesch

**Comment by lexvz14** [comment] 2024-04-26 09:50
Hi there,

I got the error too using PostgreSQL and 3.0.0-beta.15. Local build works like a charm, Vercel throws 405 error as I am trying to log in.

I've tried multiple rebuilds, but no luck so far..

**Comment by lexvz14** [comment] 2024-04-26 10:18
Same issue on 3.0.0-beta.18..

**Comment by denolfe** [comment] 2024-04-26 10:56
Reopening for investigation. Many people seeing this in latest beta.

**Comment by JarrodMFlesch** [comment] 2024-04-26 12:11
@lexvz14 does you app have the OPTIONS method exported inside `/app/(payload)/api/[...slug]/route.ts`? That was recently added and might be missing in your file. You can see what it looks like on the demo repo here: https://github.com/payloadcms/payload-3.0-demo/blob/main/src/app/(payload)/api/%5B...slug%5D/route.ts

**Comment by Rhys97W** [comment] 2024-04-26 12:57
I have made my route.ts identical and still yields the same results of the status 405 when logging in.

**Comment by schminkel** [comment] 2024-04-26 14:18
I've encountered a "405 Method Not Allowed" error on login while attempting a straightforward reproduction.

Here's how I set up the environment:

* Created a free cluster on Atlas MongoDB with unrestricted network access.
* Configured a custom domain using a CNAME record (payloadcms.xtra.tools).
* Set up the environment variables as follows:
NEXT_PUBLIC_PAYLOAD_URL=https://payloadcms.xtra.tools/
PAYLOAD_SECRET=jerliejfilwajefSEANlawefawfewag349jwgo4gj5w
MONGODB_URI=mongodb+srv://schminkel:<password>@cluster0.0pbvkgz.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0

The repository I forked can be found here: https://github.com/schminkel/payload-3.0-demo
The application is hosted on Vercel at this address using the default login: https://payloadcms.xtra.tools/admin

However, I'm unable to log in due to the 405 error. Any ideas?

**Comment by siobahnschuck** [comment] 2024-04-26 20:20
Having the same `405 Method Not Allowed` on login ONLY on deploys from Vercel, locally it is fine. This just started happening today with no upgrade to payload currently still on `3.0.0-beta.9` . Redeploying the branches doesn't have any effect. Has anyone found a solid solution for this?

**Comment by denolfe** [comment] 2024-04-26 22:46
We're looking into this one. Tried a release earlier with a possible fix but still was showing the same issue.

This is the top of our list!

**Comment by jmikrut** [comment] 2024-04-26 22:56
Interesting, old betas show the same issue? Maybe we need to raise this with Vercel

**Comment by EAlexsun** [comment] 2024-04-26 23:47
Same issue on 3.0.0-beta.19

**Comment by kylefraser** [comment] 2024-04-27 13:11
after having all the same issues as listed above, I was able to get in this morning after running a new build. 

next: 14.3.0-canary.26
payload: 3.0.0-beta.18

**Comment by bourquep** [comment] 2024-04-27 13:13
Started seeing this error this morning as well worked fine before and I did not change anything significant to my app.

```
"next": "14.2.2",
"payload": "3.0.0-beta.11"
```

**Comment by bourquep** [comment] 2024-04-27 13:25
Seems like it could be a Vercel issue: I have just redeployed my latest deployment (which exhibited the 405 issue), and it works now 🤷🏻‍♂️

**Comment by jmikrut** [comment] 2024-04-27 14:23
Yep. I just redeployed as well and the issue fixed itself. Probably a Vercel thing. We'll keep an eye on it but for anyone else having this issue, please try and redeploy to Vercel. Problem just fixed itself in all of my tests!

**Closed by jmikrut** 2024-04-27 14:23 UTC

**Comment by schminkel** [comment] 2024-04-27 14:41
Yes, just redeployed and it is working!

**Comment by vixalien** [comment] 2024-04-29 08:28
Since this issue goes away when you redeploy, I'm assuming it's caused by some pre-existing build cache on Vercel's side.

**Comment by goodallman** [comment] 2024-05-06 08:19
Well, I am getting this error on localhost now :/ I am on 3.0.0-beta.24.

From what I saw, it's only happening on record creation, and only if I have a relation field in there. Everything else is working as it should.
